export const BASE_IPFS_URI ='ipfs://';

// Collection metadata
export const SQUAD_METADATA_ARIA = BASE_IPFS_URI + 'QmRP3ni859zcvPyqT177iCP13maHYfGpU4J8AMd9D5C6ww';
export const SQUAD_METADATA_LUNA = BASE_IPFS_URI + 'QmZBcZa8SoteyCdfjoB71HBwgqjh9aftgux2eWTdBaXM5h';
export const SQUAD_METADATA_RYKER = BASE_IPFS_URI + 'QmX6f1CsaFYdrchTVsknZqAaBdBRUWDsdCmGQNsrqkEzdy';
export const SQUAD_METADATA_THADDEUS = BASE_IPFS_URI + 'QmQhanJfr3md56iRNZ9JoE1nkENRByFjtAjN73FGMjxTwp';

export const SQUAD_ITEM_METADATA_ARIA_BODY = BASE_IPFS_URI + 'QmWBoGjxqkvfJMm7vcNayVCkRNpGXC5wZiJab2hEAzJozE';
export const SQUAD_ITEM_METADATA_ARIA_HEAD = BASE_IPFS_URI + 'QmRQYACKTtBgid5Xou7Fmub7JBeG6ikTD8yaFWjEMSecHD';
export const SQUAD_ITEM_METADATA_ARIA_LEFT_HAND = BASE_IPFS_URI + 'QmRvkqfLKyg3e12fX8JifDniS5dRcxtrqZRcpiyQpyPtwC';
export const SQUAD_ITEM_METADATA_ARIA_RIGHT_HAND = BASE_IPFS_URI + 'QmVPw2NDvBN21DGov26KdU5UXayxNugEF3YNJANfeFV4Rj';

export const SQUAD_ITEM_METADATA_LUNA_BODY = BASE_IPFS_URI + 'QmcTLziAaUVzCr7UFnSwbaLGtwtGXej7mm8u1ejc6bC6qH';
export const SQUAD_ITEM_METADATA_LUNA_HEAD = BASE_IPFS_URI + 'QmcrsPZHWtRT7PNutZ9C5b14Xqw8E4Raem9AUtEKPuVMPE';
export const SQUAD_ITEM_METADATA_LUNA_LEFT_HAND = BASE_IPFS_URI + 'QmXpVcS1GERXpcqp1ac9tKzojn17T3Sn3wt2q4QreqMKXY';
export const SQUAD_ITEM_METADATA_LUNA_RIGHT_HAND = BASE_IPFS_URI + 'QmQZw5vyQGnvZF72zbCaj2o2r6pjE3aAj73E5iRrQwvnen';

export const SQUAD_ITEM_METADATA_RYKER_BODY = BASE_IPFS_URI + 'QmWMcyVZRpCL4WeG8JNhChmzda5tWtjdFbgZ3nduVogxnL';
export const SQUAD_ITEM_METADATA_RYKER_HEAD = BASE_IPFS_URI + 'QmNnCxLBGRzCBq8zK8Lre1qrDHuo9G7FLGjs7Njgw94GVS';
export const SQUAD_ITEM_METADATA_RYKER_LEFT_HAND = BASE_IPFS_URI + 'QmZgCkTWywYRVEVBUAUMcwEcKr7vrNgrHqNuJMMcz8YYCp';
export const SQUAD_ITEM_METADATA_RYKER_RIGHT_HAND = BASE_IPFS_URI + 'QmNVbSWPqKGDdhCDXaU4wZdsCyZUmEtRk731WzxqgZyUkk';

export const SQUAD_ITEM_METADATA_THADDEUS_BODY = BASE_IPFS_URI + 'QmbVTH1QqphHSQKqNx2qmNsnyeaGv5Jnpyrt4kXVun9HLr';
export const SQUAD_ITEM_METADATA_THADDEUS_HEAD = BASE_IPFS_URI + 'Qmer6zDaLdxJZUpKk5s7RuvzwAw1KctxeBUxMBN2BgYohm';
export const SQUAD_ITEM_METADATA_THADDEUS_LEFT_HAND = BASE_IPFS_URI + 'QmXyUjNbhVnyMWgVrRwuH4PiwzkSdnoGEnG2Q82AHLBMLS';
export const SQUAD_ITEM_METADATA_THADDEUS_RIGHT_HAND = BASE_IPFS_URI + 'QmNiXoCPQEeHWu5CQUjVTdYknB3HyXJ3YcJbiTZmYY1V1X';



// Catalog metadata
export const SQUAD_CATALOG_ARIA_METADATA = BASE_IPFS_URI + 'QmYJ2HhL94wcsoVu22whq99UKK2AN2TjRitnMd4wZ9AzdC';
export const SQUAD_CATALOG_LUNA_METADATA = BASE_IPFS_URI + 'QmXM4ta9ywGgjnW6QLqoBASykoAYYx1xdZY5tidiC3cENb';
export const SQUAD_CATALOG_RYKER_METADATA = BASE_IPFS_URI + 'QmbmvsxbCgV6BNc9cMYgSWtNrzDncPgBQNPSbyS6Bhfs6c';
export const SQUAD_CATALOG_THADDEUS_METADATA = BASE_IPFS_URI + 'QmYZyfT5U1WA7vUqNhiWEgTWbJC3soxfN8ye6tL6JmJpSS';
export const CATALOG_TYPE = `model/gltf-binary`;

//SLOT METADATA
export const SQUAD_ITEM_BODY_SLOT_METADATA = BASE_IPFS_URI + 'QmbgVSvL1euHa44hDanXJg9ee1pveGqfLV69AYPvpifrJx/body.json';
export const SQUAD_ITEM_HEAD_SLOT_METADATA = BASE_IPFS_URI + 'QmbgVSvL1euHa44hDanXJg9ee1pveGqfLV69AYPvpifrJx/head.json';
export const SQUAD_ITEM_LEFT_SLOT_METADATA = BASE_IPFS_URI + 'QmbgVSvL1euHa44hDanXJg9ee1pveGqfLV69AYPvpifrJx/left_hand.json';
export const SQUAD_ITEM_RIGHT_SLOT_METADATA = BASE_IPFS_URI + 'QmbgVSvL1euHa44hDanXJg9ee1pveGqfLV69AYPvpifrJx/right_hand.json';


// FIXED PARTS 
export const FIXED_PART_PARENT_ID = 1n;

// SLOT PARTS
export const SQUAD_BODY_SLOT_PART_ID = 1001n;
export const SQUAD_HEAD_SLOT_PART_ID = 1002n;
export const SQUAD_LEFT_HAND_SLOT_PART_ID = 1003n;
export const SQUAD_RIGHT_HAND_SLOT_PART_ID = 1004n;


// PART TYPES (Defined by standard)
export const PART_TYPE_SLOT = 1n;
export const PART_TYPE_FIXED = 2n;



//ENUMERATE MINT  cartella da 10k
export const MINT_ENUMERATE_ARIA = `${BASE_IPFS_URI}QmeAzBphXkUhoJCSTLiSDkwLEhApXCwRmFaRGt7qh5DyfL/`; 
export const MINT_ENUMERATE_LUNA = `${BASE_IPFS_URI}QmSjxLw6rvizFc4A7m4N2LA73zRSsccp7gFxkyfXnUPR8m/`; 
export const MINT_ENUMERATE_RYKER = `${BASE_IPFS_URI}QmNVU57Ygy4Z8xHczfWX7qPrYVnWtsHa72PRDaxgJ76a81/`; 
export const MINT_ENUMERATE_THADDEUS = `${BASE_IPFS_URI}QmdYefJyvmV4tBAE2e832tMQi1XU3yoRxwTPL2AuxF5ehh/`; 

export const FIXED_PART_ARIA_METADATA = `${MINT_ENUMERATE_ARIA}1.json`;
export const FIXED_PART_LUNA_METADATA = `${MINT_ENUMERATE_LUNA}1.json`;
export const FIXED_PART_RYKER_METADATA = `${MINT_ENUMERATE_RYKER}1.json`;
export const FIXED_PART_THADDEUS_METADATA = `${MINT_ENUMERATE_THADDEUS}1.json`;

export const ARIA_ASSET_METADATA_URI = `${MINT_ENUMERATE_ARIA}1.json`;
export const LUNA_ASSET_METADATA_URI = `${MINT_ENUMERATE_LUNA}1.json`;
export const RYKER_ASSET_METADATA_URI = `${MINT_ENUMERATE_RYKER}1.json`;
export const THADDEUS_ASSET_METADATA_URI = `${MINT_ENUMERATE_THADDEUS}1.json`;





export const ARIA_ASSET_METADATA_BODY_URI_1 = `${BASE_IPFS_URI}QmXxsbKs9XwP3G9efGMbaRWwAvbXdjJKMBhKB6nh61XBLQ`;  //primary asset
export const ARIA_ASSET_METADATA_BODY_URI_2 = `${BASE_IPFS_URI}QmdbVdm5LhJdiPaUwpXL7cvRHjkN9nfYNm5prKgkvbnU4r`;  //secondary asset
export const ARIA_ASSET_METADATA_HEAD_URI_1 = `${BASE_IPFS_URI}QmXxsbKs9XwP3G9efGMbaRWwAvbXdjJKMBhKB6nh61XBLQ`;  //primary asset
export const ARIA_ASSET_METADATA_HEAD_URI_2 = `${BASE_IPFS_URI}QmdbVdm5LhJdiPaUwpXL7cvRHjkN9nfYNm5prKgkvbnU4r`;  //secondary asset
export const ARIA_ASSET_METADATA_LEFT_HAND_URI_1 = `${BASE_IPFS_URI}QmXxsbKs9XwP3G9efGMbaRWwAvbXdjJKMBhKB6nh61XBLQ`;  //primary asset
export const ARIA_ASSET_METADATA_LEFT_HAND_URI_2 = `${BASE_IPFS_URI}QmdbVdm5LhJdiPaUwpXL7cvRHjkN9nfYNm5prKgkvbnU4r`;  //secondary asset
export const ARIA_ASSET_METADATA_RIGHT_HAND_URI_1 = `${BASE_IPFS_URI}QmXxsbKs9XwP3G9efGMbaRWwAvbXdjJKMBhKB6nh61XBLQ`;  //primary asset
export const ARIA_ASSET_METADATA_RIGHT_HAND_URI_2 = `${BASE_IPFS_URI}QmdbVdm5LhJdiPaUwpXL7cvRHjkN9nfYNm5prKgkvbnU4r`;  //secondary asset

export const LUNA_ASSET_METADATA_BODY_URI_1 = `${BASE_IPFS_URI}Qmcxvk1v9BC99AqtyrHxUdUabUW4e5sWKhdZeGsgkXNdaW`;  //primary asset
export const LUNA_ASSET_METADATA_BODY_URI_2 = `${BASE_IPFS_URI}QmcZRoCMEYEE3rthU1Fcn1Eg66qTqdtYZPv1zs7FUEqHyD`;  //secondary asset
export const LUNA_ASSET_METADATA_HEAD_URI_1 = `${BASE_IPFS_URI}Qmcxvk1v9BC99AqtyrHxUdUabUW4e5sWKhdZeGsgkXNdaW`;  //primary asset
export const LUNA_ASSET_METADATA_HEAD_URI_2 = `${BASE_IPFS_URI}QmcZRoCMEYEE3rthU1Fcn1Eg66qTqdtYZPv1zs7FUEqHyD`;  //secondary asset
export const LUNA_ASSET_METADATA_LEFT_HAND_URI_1 = `${BASE_IPFS_URI}Qmcxvk1v9BC99AqtyrHxUdUabUW4e5sWKhdZeGsgkXNdaW`;  //primary asset
export const LUNA_ASSET_METADATA_LEFT_HAND_URI_2 = `${BASE_IPFS_URI}QmcZRoCMEYEE3rthU1Fcn1Eg66qTqdtYZPv1zs7FUEqHyD`;  //secondary asset
export const LUNA_ASSET_METADATA_RIGHT_HAND_URI_1 = `${BASE_IPFS_URI}Qmcxvk1v9BC99AqtyrHxUdUabUW4e5sWKhdZeGsgkXNdaW`;  //primary asset
export const LUNA_ASSET_METADATA_RIGHT_HAND_URI_2 = `${BASE_IPFS_URI}QmcZRoCMEYEE3rthU1Fcn1Eg66qTqdtYZPv1zs7FUEqHyD`;  //secondary asset

export const RYKER_ASSET_METADATA_BODY_URI_1 = `${BASE_IPFS_URI}QmUfSu5RUku8BU5DQRsPZKLabBCNQ6hzKsHJmMPrYiQHWP`;  //primary asset
export const RYKER_ASSET_METADATA_BODY_URI_2 = `${BASE_IPFS_URI}QmcvH2PKiCAEah4Y2e2A9SwanLHiJKCW6a2yhYyme52iYh`;  //secondary asset
export const RYKER_ASSET_METADATA_HEAD_URI_1 = `${BASE_IPFS_URI}QmUfSu5RUku8BU5DQRsPZKLabBCNQ6hzKsHJmMPrYiQHWP`;  //primary asset
export const RYKER_ASSET_METADATA_HEAD_URI_2 = `${BASE_IPFS_URI}QmcvH2PKiCAEah4Y2e2A9SwanLHiJKCW6a2yhYyme52iYh`;  //secondary asset
export const RYKER_ASSET_METADATA_LEFT_HAND_URI_1 = `${BASE_IPFS_URI}QmUfSu5RUku8BU5DQRsPZKLabBCNQ6hzKsHJmMPrYiQHWP`;  //primary asset
export const RYKER_ASSET_METADATA_LEFT_HAND_URI_2 = `${BASE_IPFS_URI}QmcvH2PKiCAEah4Y2e2A9SwanLHiJKCW6a2yhYyme52iYh`;  //secondary asset
export const RYKER_ASSET_METADATA_RIGHT_HAND_URI_1 = `${BASE_IPFS_URI}QmUfSu5RUku8BU5DQRsPZKLabBCNQ6hzKsHJmMPrYiQHWP`;  //primary asset
export const RYKER_ASSET_METADATA_RIGHT_HAND_URI_2 = `${BASE_IPFS_URI}QmcvH2PKiCAEah4Y2e2A9SwanLHiJKCW6a2yhYyme52iYh`;  //secondary asset


export const THADDEUS_ASSET_METADATA_BODY_URI_1 = `${BASE_IPFS_URI}QmQkcyVohhCP4QcNGGcaZz6tty8SQjkewpith2hazZALsb`;  //primary asset
export const THADDEUS_ASSET_METADATA_BODY_URI_2 = `${BASE_IPFS_URI}QmVKyJTGiwGG36xoNTXGxPpL44z3PUdexrmodWQrgfy3bT`;  //secondary asset
export const THADDEUS_ASSET_METADATA_HEAD_URI_1 = `${BASE_IPFS_URI}QmQkcyVohhCP4QcNGGcaZz6tty8SQjkewpith2hazZALsb`;  //primary asset
export const THADDEUS_ASSET_METADATA_HEAD_URI_2 = `${BASE_IPFS_URI}QmVKyJTGiwGG36xoNTXGxPpL44z3PUdexrmodWQrgfy3bT`;  //secondary asset
export const THADDEUS_ASSET_METADATA_LEFT_HAND_URI_1 = `${BASE_IPFS_URI}QmQkcyVohhCP4QcNGGcaZz6tty8SQjkewpith2hazZALsb`;  //primary asset
export const THADDEUS_ASSET_METADATA_LEFT_HAND_URI_2 = `${BASE_IPFS_URI}QmVKyJTGiwGG36xoNTXGxPpL44z3PUdexrmodWQrgfy3bT`;  //secondary asset
export const THADDEUS_ASSET_METADATA_RIGHT_HAND_URI_1 = `${BASE_IPFS_URI}QmQkcyVohhCP4QcNGGcaZz6tty8SQjkewpith2hazZALsb`;  //primary asset
export const THADDEUS_ASSET_METADATA_RIGHT_HAND_URI_2 = `${BASE_IPFS_URI}QmVKyJTGiwGG36xoNTXGxPpL44z3PUdexrmodWQrgfy3bT`;  //secondary asset


// Equippable groups  todo forse qui il doppio bug?
export const EQUIPPABLE_GROUP_FOR_SQUAD_DEFAULT = 1; //tutti saranno equipaggiabili
export const EQUIPPABLE_GROUP_FOR_ITEMS_LEFT_HAND = SQUAD_LEFT_HAND_SLOT_PART_ID;
export const EQUIPPABLE_GROUP_FOR_ITEMS_RIGHT_HAND = SQUAD_RIGHT_HAND_SLOT_PART_ID;
export const EQUIPPABLE_GROUP_FOR_ITEMS_BODY = SQUAD_BODY_SLOT_PART_ID;
export const EQUIPPABLE_GROUP_FOR_ITEMS_HEAD = SQUAD_HEAD_SLOT_PART_ID;


// Z INDEXES per le immagini SVG (sia fixed che slot part), avendo lo stesso valore allora hanno lo stesso livello
export const Z_INDEX_BACKGROUND = 0n;
export const Z_INDEX_BODY_ITEMS = 2n;
export const Z_INDEX_HEAD_ITEMS = 4n;
export const Z_INDEX_LEFT_HAND_ITEMS = 6n;
export const Z_INDEX_RIGHT_HAND_ITEMS = 8n;
